### ISSUE TITLE
Error [line 13190]: out of memory in tree_malloc()

### ISSUE THREAD

**Issue by gzimh** [jfisteus/html2xhtml#17]
I'm getting this error when testing with a ~25mb html file.

**Comment by jfisteus** [comment]
The program should work with files of that size. There must be a bug somewhere... If you can place the HTML file somewhere I can download it, I'll take look to the problem when I get some free time I can dedicate to this. It might take time though, since I'm no longer interested in maintaining html2xhtml, and already have a very limited amount of time to dedicate to other projects I actively maintain.
